// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CitationSchema = {
    properties: {
        source: {
            type: 'string',
            title: 'Source'
        }
    },
    type: 'object',
    required: ['source'],
    title: 'Citation',
    description: 'A single Repository source backing an answer.'
} as const;

export const CodingRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            '$ref': '#/components/schemas/CodingRunStatus'
        },
        failed_stage: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CodingRunStage'
                },
                {
                    type: 'null'
                }
            ]
        },
        failure_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failure Reason'
        },
        review_findings: {
            items: {
                '$ref': '#/components/schemas/ReviewFinding'
            },
            type: 'array',
            title: 'Review Findings'
        },
        diff: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diff'
        },
        disclaimer: {
            type: 'string',
            title: 'Disclaimer',
            default: 'These tests were not executed and their runtime correctness was not verified; the patch was assessed statically only.'
        }
    },
    type: 'object',
    required: ['id', 'status'],
    title: 'CodingRunPublic',
    description: `Post-stream read of a Coding Run's persisted lifecycle, review, and failure state.

\`\`disclaimer\`\` restates that the generated tests were not executed and their
runtime correctness was not verified — the Patch Review was static only.`
} as const;

export const CodingRunStageSchema = {
    type: 'string',
    enum: ['planning', 'retrieving', 'generating', 'reviewing', 'git_commit', 'git_push'],
    title: 'CodingRunStage',
    description: 'A working stage a Coding Run can fail at, recorded as ``failed_stage``.'
} as const;

export const CodingRunStatusSchema = {
    type: 'string',
    enum: ['queued', 'planning', 'retrieving', 'generating', 'awaiting_review', 'reviewing', 'awaiting_approval', 'changes_requested', 'approved', 'succeeded', 'rejected', 'failed'],
    title: 'CodingRunStatus',
    description: `The lifecycle states of a Coding Run.

This issue drives a run through \`\`queued -> planning -> retrieving\`\` and to
\`\`failed\`\` on a rejected scope; the later states are the planned vocabulary
that subsequent stages (generation, review, application) advance into.`
} as const;

export const ExternalReferenceSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url',
            description: 'URL of the consulted external source.'
        },
        title: {
            type: 'string',
            title: 'Title',
            description: 'Human-readable title of the external source.',
            default: ''
        }
    },
    type: 'object',
    required: ['url'],
    title: 'ExternalReference',
    description: 'A web result consulted for test-writing guidance, kept apart from Repository Documents.'
} as const;

export const GeneratedFileSchema = {
    properties: {
        path: {
            type: 'string',
            title: 'Path',
            description: 'Repository-relative path of the test file to write.'
        },
        content: {
            type: 'string',
            title: 'Content',
            description: 'The complete contents of the test file.'
        }
    },
    type: 'object',
    required: ['path', 'content'],
    title: 'GeneratedFile',
    description: 'One complete proposed file: a checkout-relative path and its full contents.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HumanDecisionRequestSchema = {
    properties: {
        coding_run_id: {
            type: 'string',
            format: 'uuid',
            title: 'Coding Run Id'
        },
        approved: {
            type: 'boolean',
            title: 'Approved'
        },
        feedback: {
            type: 'string',
            maxLength: 4000,
            title: 'Feedback',
            default: ''
        }
    },
    type: 'object',
    required: ['coding_run_id', 'approved'],
    title: 'HumanDecisionRequest',
    description: `The owner's human-in-the-loop decision on a reviewed Test Patch.

Delivered through the same session stream that produced the patch: it resumes
the suspended Coding Run rather than starting a new one. \`\`approved\`\` is the
verdict; a rejection discards the patch.`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'A simple ``{"message": ...}`` response body.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'A password-reset submission pairing the reset token with the new password.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate',
    description: 'Payload for the local-only user creation endpoint.'
} as const;

export const RepositoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RepositoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RepositoriesPublic',
    description: 'A page of repositories with the total count.'
} as const;

export const RepositoryCreateSchema = {
    properties: {
        token: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Token'
        },
        token_expiration_days: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Expiration Days'
        },
        repository_url: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Repository Url'
        }
    },
    type: 'object',
    required: ['token', 'repository_url'],
    title: 'RepositoryCreate',
    description: 'Registration payload: a repository URL plus its access token.'
} as const;

export const RepositoryProviderSchema = {
    type: 'string',
    enum: ['github'],
    title: 'RepositoryProvider',
    description: 'Supported Git hosting providers.'
} as const;

export const RepositoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        repository_url: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Repository Url'
        },
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        provider: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RepositoryProvider',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ]
        },
        owner: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Owner'
        },
        default_branch: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Branch'
        },
        indexed_commit_sha: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 40
                },
                {
                    type: 'null'
                }
            ],
            title: 'Indexed Commit Sha'
        },
        status: {
            '$ref': '#/components/schemas/RepositoryStatus'
        },
        failed_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed Reason'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'repository_url', 'name', 'owner', 'status', 'failed_reason', 'created_at', 'updated_at'],
    title: 'RepositoryPublic',
    description: 'A repository as exposed to clients, without the stored token.'
} as const;

export const RepositoryQuestionRequestSchema = {
    properties: {
        question: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 4000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Question'
        },
        decision: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/HumanDecisionRequest'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'RepositoryQuestionRequest',
    description: `One turn on a session stream: a new question or a decision resuming a paused run.

The same entry point both asks a repository-grounded/code-generation question and
delivers the owner's human-in-the-loop decision, so exactly one of \`\`question\`\` or
\`\`decision\`\` must be present — never both, never neither.`
} as const;

export const RepositorySessionCreateSchema = {
    properties: {
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title',
            default: 'New session'
        }
    },
    type: 'object',
    required: ['repository_id'],
    title: 'RepositorySessionCreate',
    description: 'Payload to open a session bound to a repository.'
} as const;

export const RepositorySessionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        repository_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repository Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'owner_id', 'repository_id', 'created_at', 'updated_at'],
    title: 'RepositorySessionPublic',
    description: 'A session as exposed to clients.'
} as const;

export const RepositorySessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RepositorySessionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RepositorySessionsPublic',
    description: 'A page of sessions with the total count.'
} as const;

export const RepositoryStatusSchema = {
    type: 'string',
    enum: ['pending', 'cloning', 'indexing', 'ready', 'failed'],
    title: 'RepositoryStatus',
    description: 'Lifecycle of a repository from registration through clone, index, and ready.'
} as const;

export const RepositoryUpdateSchema = {
    properties: {
        token: {
            type: 'string',
            maxLength: 2048,
            minLength: 1,
            title: 'Token'
        },
        token_expiration_days: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Expiration Days'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'RepositoryUpdate',
    description: 'Update payload supplying a new access token and optional expiry.'
} as const;

export const ReviewFindingSchema = {
    properties: {
        category: {
            type: 'string',
            enum: ['coverage', 'readability', 'conventions', 'imports', 'scope', 'versioning'],
            title: 'Category',
            description: 'The review concern this finding falls under.'
        },
        detail: {
            type: 'string',
            title: 'Detail',
            description: 'A human-readable explanation of the finding.'
        }
    },
    type: 'object',
    required: ['category', 'detail'],
    title: 'ReviewFinding',
    description: 'One categorized, human-readable observation about a proposed Test Patch.'
} as const;

export const RunPatchPublicSchema = {
    properties: {
        coding_run_id: {
            type: 'string',
            format: 'uuid',
            title: 'Coding Run Id'
        },
        diff: {
            type: 'string',
            title: 'Diff'
        },
        generated_files: {
            items: {
                '$ref': '#/components/schemas/GeneratedFile'
            },
            type: 'array',
            title: 'Generated Files'
        },
        external_references: {
            items: {
                '$ref': '#/components/schemas/ExternalReference'
            },
            type: 'array',
            title: 'External References'
        }
    },
    type: 'object',
    required: ['coding_run_id', 'diff'],
    title: 'RunPatchPublic',
    description: "Post-stream read of a Coding Run's persisted Test Patch content."
} as const;

export const SessionHistoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SessionHistoryPublic'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: ['data'],
    title: 'SessionHistoriesPublic',
    description: "A session's full message history."
} as const;

export const SessionHistoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        role: {
            '$ref': '#/components/schemas/SessionMessageRole'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        citations: {
            items: {
                '$ref': '#/components/schemas/Citation'
            },
            type: 'array',
            title: 'Citations'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'role', 'content', 'citations', 'position', 'created_at'],
    title: 'SessionHistoryPublic',
    description: 'One persisted session message as exposed to clients.'
} as const;

export const SessionMessageRoleSchema = {
    type: 'string',
    enum: ['user', 'assistant'],
    title: 'SessionMessageRole',
    description: 'Author of a session history message.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'An OAuth2 access-token response.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Self-service password change, verifying the current password.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Admin payload to create a user with a plaintext password.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'A user as exposed to clients, without the password hash.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Self-service signup payload.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Admin payload to update a user; all fields optional.'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: "Self-service update of one's own name and email."
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'A page of users with the total count.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;