// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, RepositoriesReadRepositoriesData, RepositoriesReadRepositoriesResponse, RepositoriesCreateRepositoryData, RepositoriesCreateRepositoryResponse, RepositoriesReadRepositoryData, RepositoriesReadRepositoryResponse, RepositoriesUpdateRepositoryData, RepositoriesUpdateRepositoryResponse, RepositoriesDeleteRepositoryData, RepositoriesDeleteRepositoryResponse, SessionsCreateRepositorySessionData, SessionsCreateRepositorySessionResponse, SessionsReadRepositorySessionsData, SessionsReadRepositorySessionsResponse, SessionsAskRepositoryQuestionData, SessionsAskRepositoryQuestionResponse, SessionsReadRepositorySessionHistoryData, SessionsReadRepositorySessionHistoryResponse, SessionsReadCodingRunData, SessionsReadCodingRunResponse, SessionsReadCodingRunPatchData, SessionsReadCodingRunPatchResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RepositoriesService {
    /**
     * Read Repositories
     * Return a paginated Git repository list visible to the current user.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns RepositoriesPublic Successful Response
     * @throws ApiError
     */
    public static readRepositories(data: RepositoriesReadRepositoriesData = {}): CancelablePromise<RepositoriesReadRepositoriesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/repositories/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Repository
     * Register a Git repository and schedule its cloning and indexing.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns RepositoryPublic Successful Response
     * @throws ApiError
     */
    public static createRepository(data: RepositoriesCreateRepositoryData): CancelablePromise<RepositoriesCreateRepositoryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/repositories/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Repository
     * Return one Git repository after enforcing ownership permissions.
     * @param data The data for the request.
     * @param data.repositoryId
     * @returns RepositoryPublic Successful Response
     * @throws ApiError
     */
    public static readRepository(data: RepositoriesReadRepositoryData): CancelablePromise<RepositoriesReadRepositoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/repositories/{repository_id}',
            path: {
                repository_id: data.repositoryId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Repository
     * Replace only Git repository credentials.
     * @param data The data for the request.
     * @param data.repositoryId
     * @param data.requestBody
     * @returns void Successful Response
     * @throws ApiError
     */
    public static updateRepository(data: RepositoriesUpdateRepositoryData): CancelablePromise<RepositoriesUpdateRepositoryResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/repositories/{repository_id}',
            path: {
                repository_id: data.repositoryId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Repository
     * Delete Git repository state from local checkout, vector db, and relational db.
     * @param data The data for the request.
     * @param data.repositoryId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteRepository(data: RepositoriesDeleteRepositoryData): CancelablePromise<RepositoriesDeleteRepositoryResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/repositories/{repository_id}',
            path: {
                repository_id: data.repositoryId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SessionsService {
    /**
     * Create Repository Session
     * Open a new session bound to a repository the caller can access.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns RepositorySessionPublic Successful Response
     * @throws ApiError
     */
    public static createRepositorySession(data: SessionsCreateRepositorySessionData): CancelablePromise<SessionsCreateRepositorySessionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sessions',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Repository Sessions
     * List the caller's Repository Sessions, optionally filtered by Repository.
     * @param data The data for the request.
     * @param data.repositoryId
     * @param data.skip
     * @param data.limit
     * @returns RepositorySessionsPublic Successful Response
     * @throws ApiError
     */
    public static readRepositorySessions(data: SessionsReadRepositorySessionsData = {}): CancelablePromise<SessionsReadRepositorySessionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sessions',
            query: {
                repository_id: data.repositoryId,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Ask Repository Question
     * Infer the Request Intent and stream the routed Agent Stream for an owned session.
     *
     * The same entry point serves a repository-grounded answer, a Code Generation Task,
     * and the owner's human-in-the-loop decision on a reviewed patch; the unified graph's
     * ``classify`` node decides the first two, while a ``decision`` resumes the suspended
     * run that produced the patch. A fresh question gets its own checkpointer ``thread_id``;
     * a decision reuses the paused run's own thread.
     * @param data The data for the request.
     * @param data.repositorySessionId
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static askRepositoryQuestion(data: SessionsAskRepositoryQuestionData): CancelablePromise<SessionsAskRepositoryQuestionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sessions/{repository_session_id}/questions',
            path: {
                repository_session_id: data.repositorySessionId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Repository Session History
     * Return the recent message history of an owned session.
     * @param data The data for the request.
     * @param data.repositorySessionId
     * @returns SessionHistoriesPublic Successful Response
     * @throws ApiError
     */
    public static readRepositorySessionHistory(data: SessionsReadRepositorySessionHistoryData): CancelablePromise<SessionsReadRepositorySessionHistoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sessions/{repository_session_id}/history',
            path: {
                repository_session_id: data.repositorySessionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Coding Run
     * Read an owned Coding Run's persisted state, review findings, and failure information.
     *
     * Serves the durable record after the ephemeral Agent Stream has closed, so a
     * client that reloads or reconnects can recover the run's outcome.
     * @param data The data for the request.
     * @param data.repositorySessionId
     * @param data.codingRunId
     * @returns CodingRunPublic Successful Response
     * @throws ApiError
     */
    public static readCodingRun(data: SessionsReadCodingRunData): CancelablePromise<SessionsReadCodingRunResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sessions/{repository_session_id}/runs/{coding_run_id}',
            path: {
                repository_session_id: data.repositorySessionId,
                coding_run_id: data.codingRunId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Coding Run Patch
     * Read an owned Coding Run's persisted Test Patch content (canonical diff and proposals).
     * @param data The data for the request.
     * @param data.repositorySessionId
     * @param data.codingRunId
     * @returns RunPatchPublic Successful Response
     * @throws ApiError
     */
    public static readCodingRunPatch(data: SessionsReadCodingRunPatchData): CancelablePromise<SessionsReadCodingRunPatchResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sessions/{repository_session_id}/runs/{coding_run_id}/patch',
            path: {
                repository_session_id: data.repositorySessionId,
                coding_run_id: data.codingRunId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Send a test email to verify SMTP configuration (superuser only).
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * Return ``True`` to signal the service is up.
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}