// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * A single Repository source backing an answer.
 */
export type Citation = {
    source: string;
};

/**
 * Post-stream read of a Coding Run's persisted lifecycle, review, and failure state.
 *
 * ``disclaimer`` restates that the generated tests were not executed and their
 * runtime correctness was not verified — the Patch Review was static only.
 */
export type CodingRunPublic = {
    id: string;
    status: CodingRunStatus;
    failed_stage?: (CodingRunStage | null);
    failure_reason?: (string | null);
    review_findings?: Array<ReviewFinding>;
    diff?: (string | null);
    pull_request_url?: (string | null);
    disclaimer?: string;
};

/**
 * A working stage a Coding Run can fail at, recorded as ``failed_stage``.
 */
export type CodingRunStage = 'planning' | 'retrieving' | 'generating' | 'reviewing' | 'git_commit' | 'git_push' | 'github_pull_request';

/**
 * The lifecycle states of a Coding Run.
 *
 * This issue drives a run through ``queued -> planning -> retrieving`` and to
 * ``failed`` on a rejected scope; the later states are the planned vocabulary
 * that subsequent stages (generation, review, application) advance into.
 */
export type CodingRunStatus = 'queued' | 'planning' | 'retrieving' | 'generating' | 'awaiting_review' | 'reviewing' | 'awaiting_approval' | 'changes_requested' | 'approved' | 'succeeded' | 'rejected' | 'failed';

/**
 * A web result consulted for test-writing guidance, kept apart from Repository Documents.
 */
export type ExternalReference = {
    /**
     * URL of the consulted external source.
     */
    url: string;
    /**
     * Human-readable title of the external source.
     */
    title?: string;
};

/**
 * One complete proposed file: a checkout-relative path and its full contents.
 */
export type GeneratedFile = {
    /**
     * Repository-relative path of the test file to write.
     */
    path: string;
    /**
     * The complete contents of the test file.
     */
    content: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * The owner's human-in-the-loop decision on a reviewed Test Patch.
 *
 * Delivered through the same session stream that produced the patch: it resumes
 * the suspended Coding Run rather than starting a new one. ``approved`` is the
 * verdict; a rejection discards the patch.
 */
export type HumanDecisionRequest = {
    coding_run_id: string;
    approved: boolean;
    feedback?: string;
};

/**
 * A simple ``{"message": ...}`` response body.
 */
export type Message = {
    message: string;
};

/**
 * A password-reset submission pairing the reset token with the new password.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Payload for the local-only user creation endpoint.
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * A page of repositories with the total count.
 */
export type RepositoriesPublic = {
    data: Array<RepositoryPublic>;
    count: number;
};

/**
 * Registration payload: a repository URL plus its access token.
 */
export type RepositoryCreate = {
    token: string;
    token_expiration_days?: (number | null);
    repository_url: string;
};

/**
 * Supported Git hosting providers.
 */
export type RepositoryProvider = 'github';

/**
 * A repository as exposed to clients, without the stored token.
 */
export type RepositoryPublic = {
    id: string;
    user_id: string;
    repository_url: string;
    name: string;
    provider?: (RepositoryProvider | null);
    owner: string;
    default_branch?: (string | null);
    indexed_commit_sha?: (string | null);
    status: RepositoryStatus;
    failed_reason: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * One turn on a session stream: a new question or a decision resuming a paused run.
 *
 * The same entry point both asks a repository-grounded/code-generation question and
 * delivers the owner's human-in-the-loop decision, so exactly one of ``question`` or
 * ``decision`` must be present — never both, never neither.
 */
export type RepositoryQuestionRequest = {
    question?: (string | null);
    decision?: (HumanDecisionRequest | null);
};

/**
 * Payload to open a session bound to a repository.
 */
export type RepositorySessionCreate = {
    repository_id: string;
    title?: string;
};

/**
 * A session as exposed to clients.
 */
export type RepositorySessionPublic = {
    id: string;
    title: string;
    user_id: string;
    repository_id: string;
    created_at: string;
    updated_at: string;
};

/**
 * A page of sessions with the total count.
 */
export type RepositorySessionsPublic = {
    data: Array<RepositorySessionPublic>;
    count: number;
};

/**
 * Lifecycle of a repository from registration through clone, index, and ready.
 */
export type RepositoryStatus = 'pending' | 'cloning' | 'indexing' | 'ready' | 'failed';

/**
 * Update payload supplying a new access token and optional expiry.
 */
export type RepositoryUpdate = {
    token: string;
    token_expiration_days?: (number | null);
};

/**
 * One categorized, human-readable observation about a proposed Test Patch.
 */
export type ReviewFinding = {
    /**
     * The review concern this finding falls under.
     */
    category: 'coverage' | 'readability' | 'conventions' | 'imports' | 'scope' | 'versioning';
    /**
     * A human-readable explanation of the finding.
     */
    detail: string;
};

/**
 * The review concern this finding falls under.
 */
export type category = 'coverage' | 'readability' | 'conventions' | 'imports' | 'scope' | 'versioning';

/**
 * Post-stream read of a Coding Run's persisted Test Patch content.
 */
export type RunPatchPublic = {
    coding_run_id: string;
    diff: string;
    generated_files?: Array<GeneratedFile>;
    external_references?: Array<ExternalReference>;
};

/**
 * A session's full message history.
 */
export type SessionHistoriesPublic = {
    data: Array<SessionHistoryPublic>;
};

/**
 * One persisted session message as exposed to clients.
 */
export type SessionHistoryPublic = {
    id: string;
    session_id: string;
    role: SessionMessageRole;
    content: string;
    citations: Array<Citation>;
    position: number;
    coding_run_id?: (string | null);
    created_at: string;
};

/**
 * Author of a session history message.
 */
export type SessionMessageRole = 'user' | 'assistant';

/**
 * An OAuth2 access-token response.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Self-service password change, verifying the current password.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Admin payload to create a user with a plaintext password.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * A user as exposed to clients, without the password hash.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * Self-service signup payload.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * A page of users with the total count.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Admin payload to update a user; all fields optional.
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Self-service update of one's own name and email.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RepositoriesReadRepositoriesData = {
    limit?: number;
    skip?: number;
};

export type RepositoriesReadRepositoriesResponse = (RepositoriesPublic);

export type RepositoriesCreateRepositoryData = {
    requestBody: RepositoryCreate;
};

export type RepositoriesCreateRepositoryResponse = (RepositoryPublic);

export type RepositoriesReadRepositoryData = {
    repositoryId: string;
};

export type RepositoriesReadRepositoryResponse = (RepositoryPublic);

export type RepositoriesUpdateRepositoryData = {
    repositoryId: string;
    requestBody: RepositoryUpdate;
};

export type RepositoriesUpdateRepositoryResponse = (void);

export type RepositoriesDeleteRepositoryData = {
    repositoryId: string;
};

export type RepositoriesDeleteRepositoryResponse = (void);

export type SessionsCreateRepositorySessionData = {
    requestBody: RepositorySessionCreate;
};

export type SessionsCreateRepositorySessionResponse = (RepositorySessionPublic);

export type SessionsReadRepositorySessionsData = {
    limit?: number;
    repositoryId?: (string | null);
    skip?: number;
};

export type SessionsReadRepositorySessionsResponse = (RepositorySessionsPublic);

export type SessionsAskRepositoryQuestionData = {
    repositorySessionId: string;
    requestBody: RepositoryQuestionRequest;
};

export type SessionsAskRepositoryQuestionResponse = (unknown);

export type SessionsReadRepositorySessionHistoryData = {
    repositorySessionId: string;
};

export type SessionsReadRepositorySessionHistoryResponse = (SessionHistoriesPublic);

export type SessionsReadCodingRunData = {
    codingRunId: string;
    repositorySessionId: string;
};

export type SessionsReadCodingRunResponse = (CodingRunPublic);

export type SessionsReadCodingRunPatchData = {
    codingRunId: string;
    repositorySessionId: string;
};

export type SessionsReadCodingRunPatchResponse = (RunPatchPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);